apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-merge.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: inject
  name: inject
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inject
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-merge.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: inject
    spec:
      containers:
        - args:
            - --no-reports
            - -s
            - com.logimethods.smartmeter.inject.NatsInjection
          env:
            - name: DEPENDS_ON
              value: nats
            - name: GATLING_DURATION
              value: "50"
            - name: GATLING_TO_NATS_SUBJECT
              value: smartmeter.raw
            - name: GATLING_USERS_PER_SEC
              value: "500"
            - name: NATS_NAME
              value: smart-meter-nats.default.svc.cluster.local
            - name: NATS_PASSWORD
              value: natspwd_secret
            - name: NATS_USERNAME
              value: natsuser_secret
            - name: NODE_ID
              value: '"manager"'
            - name: PREDICTION_LENGTH
              value: "12"
            - name: RANDOMNESS
              value: "0.2"
            - name: SERVICE_ID
              value: '"inject"'
            - name: SERVICE_LABELS
              value: '"none"'
            - name: SERVICE_NAME
              value: '"inject"'
            - name: STREAMING_DURATION
              value: "5000"
            - name: TASK_ID
              value: '"inject_task"'
            - name: TASK_NAME
              value: '"inject_task"'
            - name: TASK_SLOT
              value: "1"
            - name: TIME_ROOT
              value: "1733661192"
          image: logimethods/smart-meter:app_inject-1.5
          name: inject
      restartPolicy: Always
